
version: '3'

services:
  redis:
    image: redis
    command: ["redis-server", "--requirepass Redis2019!", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379
    networks:
      - appNetwork

  goapp:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - appNetwork
      
networks:
  appNetwork: